# Generated by Django 5.2.7 on 2025-10-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('system', models.CharField(help_text='Ex: D&D 5e, Appel de Cthulu, Pathfinder...', max_length=100)),
            ],
        ),
    ]
