# Generated by Django 5.2.7 on 2025-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0002_universe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='creation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='JSON définissant les règles de création de personnages pour cet univers', null=True),
        ),
    ]
