# Generated by Django 5.2.7 on 2025-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.AddField(
            model_name='character',
            name='background_story',
            field=models.TextField(blank=True, verbose_name='Histoire personnelle'),
        ),
        migrations.AddField(
            model_name='character',
            name='dnd_background',
            field=models.CharField(blank=True, max_length=80, verbose_name='Historique D&D'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'équipements"),
        ),
        migrations.AddField(
            model_name='character',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Traits raciaux, capacités de classe, etc.'),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Langues parlées'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.JSONField(blank=True, default=dict, help_text='Compétences et leurs bonus'),
        ),
    ]
